name: AetherSuite
main: id.rnggagib.aethersuite.AetherSuite
version: 1.0-SNAPSHOT
api-version: 1.20
description: Modern and optimized essentials plugin with support for Paper and Folia
author: rnggagib
website: https://github.com/RanggaGibran/aethersuite